version: '3.8'

services:
  # سرویس API
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=true
      - ENVIRONMENT=development
      - MONGODB_URI=mongodb://admin:password@mongo:27020/eyeglass_recommendation?authSource=admin
      - MONGODB_DB_NAME=eyeglass_recommendation
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - WOOCOMMERCE_API_URL=https://lunato.shop/wp-json/wc/v3/products
      - WOOCOMMERCE_CONSUMER_KEY=ck_818f6ea310b3712583afc0d2f12657ae78440b38
      - WOOCOMMERCE_CONSUMER_SECRET=cs_b9e90f2f44c1f262049c7acda1933610fb182571
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # سرویس Celery Worker برای تشخیص چهره
  worker_face_detection:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 --hostname=worker_face_detection@%h --queues=face_detection
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27020/eyeglass_recommendation?authSource=admin
      - MONGODB_DB_NAME=eyeglass_recommendation
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - WOOCOMMERCE_API_URL=https://lunato.shop/wp-json/wc/v3/products
      - WOOCOMMERCE_CONSUMER_KEY=ck_818f6ea310b3712583afc0d2f12657ae78440b38
      - WOOCOMMERCE_CONSUMER_SECRET=cs_b9e90f2f44c1f262049c7acda1933610fb182571
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # سرویس Celery Worker برای تحلیل چهره
  worker_face_analysis:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 --hostname=worker_face_analysis@%h --queues=face_analysis
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27020/eyeglass_recommendation?authSource=admin
      - MONGODB_DB_NAME=eyeglass_recommendation
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - WOOCOMMERCE_API_URL=https://lunato.shop/wp-json/wc/v3/products
      - WOOCOMMERCE_CONSUMER_KEY=ck_818f6ea310b3712583afc0d2f12657ae78440b38
      - WOOCOMMERCE_CONSUMER_SECRET=cs_b9e90f2f44c1f262049c7acda1933610fb182571
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # سرویس Celery Worker برای پیشنهاد فریم
  worker_frame_matching:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 --hostname=worker_frame_matching@%h --queues=frame_matching
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27020/eyeglass_recommendation?authSource=admin
      - MONGODB_DB_NAME=eyeglass_recommendation
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - WOOCOMMERCE_API_URL=https://lunato.shop/wp-json/wc/v3/products
      - WOOCOMMERCE_CONSUMER_KEY=ck_818f6ea310b3712583afc0d2f12657ae78440b38
      - WOOCOMMERCE_CONSUMER_SECRET=cs_b9e90f2f44c1f262049c7acda1933610fb182571
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # MongoDB با تغییر پورت و تعیین کاربر و رمز عبور
  mongo:
    image: mongo:6
    ports:
      - "27020:27020"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=eyeglass_recommendation
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # Redis برای Celery
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  mongo_data: